### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by renhl717445** [collinzrj/output2prompt#2]
Hi, When I run python main0.py train system_prompts synthetic, the error is reported as follows. I've installed transformers==4.36.0, why is that? Is there anything else I need to be aware of ?
 {'loss': 2.3825, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 2.4379, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 2.1137, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 2.503, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.4223, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.1833, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.2976, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.2961, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.4075, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.0127, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 2.4486, 'learning_rate': 0.0002, 'epoch': 0.04}
Traceback (most recent call last):
  File "/home/LLM/output2prompt/main0.py", line 256, in <module>
    train(dataset_dict[dataset][0],dataset_dict[dataset][1])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LLM/output2prompt/main0.py", line 81, in train
    trainer.train()
  File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 2263, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 3003, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 840, in get_eval_dataloader
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.

**Comment by collinzrj** [comment]
Hi, I think maybe `eval_dataset` is set to None in this case, have you downloaded the `eval_dataset`?

**Comment by sjzjzyzxdyg** [comment]
I have the same question

**Comment by sjzjzyzxdyg** [comment]
> Hi, I think maybe `eval_dataset` is set to None in this case, have you downloaded the `eval_dataset`?
The eval dataset is not included in the datasets downloaded from https://zenodo.org/records/12759549.

**Comment by collinzrj** [comment]
> > The eval dataset is not included in the datasets downloaded from https://zenodo.org/records/12759549.

Have you tried this `wget "https://zenodo.org/records/12759549/files/prompt2output_datasets.zip?download=1" -O prompt2output_datasets.zip`?

**Comment by sjzjzyzxdyg** [comment]
Thank you for your reply！
I see. We don't need to verify during the training period. Just train. 
Perhaps due to the environment version, when I was running your code, I was required that the eval_dataset during training cannot be None. Just set the evaluation_strategy in training_args to "no". 
Not a big deal at all. It was just something I stumbled on.
